name: dev_releases
description: Have an overview of your favorite dev tools, frameworks or languages 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cache_image: ^1.0.5
  http: ^0.12.0+4
  shared_preferences: 0.5.6+3
  mvc_pattern:
  rive: ^0.0.1
  #flare flutter (made for rive) - https://pub.dev/packages/flare_flutter/install
  flare_flutter: ^2.0.6
  sqflite:
  intl: ^0.16.1
  flutter_markdown: ^0.3.4
  flutter_icons: 1.0.0+1
  url_launcher: ^5.4.2

  # Check that you have this dependency (added in the previous step)
  firebase_core: ^0.4.0+9

  # Add the dependency for the FlutterFire plugin for Google Analytics
  #firebase_analytics: ^5.0.2


  firebase_messaging: ^6.0.9

  firebase_crashlytics: ^0.1.3+3

  flutter_launcher_icons: ^0.7.4
  progress_dialog: ^1.2.1
  #Dynamic theme does not work yet
  #dynamic_theme: ^1.0.1
  flutter_statusbarcolor: ^0.2.3
  image_picker: ^0.6.3+4
  pull_to_refresh: 1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/fancy_github.png"
  #adaptive_icon_background: "#595959"
  #adaptive_icon_foreground: "assets/icon/fancy_github.png"
  #adaptive_icon_background: "#0B8DF7" # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "assets/icon/final_icon_white.png" # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/icon/

  #fonts:
    #- family: JetBrainsMono
    #  fonts:
    #    - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Bold.ttf
    #    - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Bold-Italic.ttf
    #    - asset: assets/fonts/JetBrainsMono/JetBrainsMono-ExtraBold.ttf
    #    - asset: assets/fonts/JetBrainsMono/JetBrainsMono-ExtraBold-Italic.ttf
    #    - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Italic.ttf
    #    - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Medium.ttf
    #    - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Medium-Italic.ttf
    #    - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Regular.ttf
    #      style: italic

    #- family: VictorMono
    #  fonts:
    #    - asset: assets/fonts/VictorMono/VictorMono-Bold.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-BoldItalic.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-BoldOblique.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-ExtraLight.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-ExtraLightItalic.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-ExtraLightOblique.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-Italic.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-Light.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-LightItalic.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-LightOblique.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-Medium.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-MediumItalic.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-MediumOblique.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-Oblique.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-Regular.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-SemiBold.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-SemiBoldItalic.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-SemiBoldOblique.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-Thin.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-ThinItalic.ttf
    #    - asset: assets/fonts/VictorMono/VictorMono-ThinOblique.ttf


    #      style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
